name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60458035527a11cc80980693784d556dbcb64a4275e5cc0c30c4f9099044e331"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "global_packs/required_data/"
