name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65ed2aec300dfd9888b65263e36f5e03c21e44f892a4de83669707fe6ad3b392"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "global_packs/required_data/"
