name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7849d70cc41e783d383a0d99b6c1b87f2ae2dd035522f40982586d1bbded4e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "global_packs/required_data/"
