#This file stores configuration options for Iris, such as the currently active shaderpack
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.5.1
enableShaders=false
